config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#index'
  resources :tops , :only => :index
  resources :quizzes
  resources :users
  resources :answers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quizzes.rb
class Quizzes < ApplicationRecord
  
  has_many :answers
  has_many :users, through: :answers
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :answers
  has_many :quizzes, through: :answers
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @quiz = Quizzes.find(params[:quizzes_id])
    @answer = Answers.new
    @answer.quizzes_id = @quizzes_id
  end

  
  def edit
    @quiz = Quizzes.find(params[:quizzes_id])
    @answer = Answers.create(create_params)
    @answer.quizzes_id = @quizzes_id
  end
  
  def update
    @quiz = Quizzes.find(params[:quizzes_id])
    @answer = Answers.create(update_params)
    @answer.quizzes_id = @quizzes_id
    @quiz.update(quizzes_params) 
    # (questions_params)はしたの記述に由来している。answer以外の内容はストロングパラメータではじくよ
  end
  
  private
  def quizzes_params
    params.require(:answer).permit(:answer,:comment,:quizzes_id, ).merge(user_id: current_user.id)
  end
  
  def create_params
    params.require(:answer).permit(:answer,:comment,:quizzes_id, ).merge(user_id: current_user.id)
  end
  
  def update_params
    params.require(:answer).permit(:answer,:comment,:quizzes_id, ).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def index
    @quiz = Quizzes.all
  end

  def new
    @quiz = Quizzes.find(params[:id])
    @answer = Answers.new
    @answer.quizzes_id = @quizzes_id
  end

  
  def edit
    @quiz = Quizzes.find(params[:quizzes_id])
    @answer = Answers.create(create_params)
    @answer.quizzes_id = @quizzes_id
  end
  
  def update
    @quiz = Quizzes.find(params[:quizzes_id])
    @answer = Answers.create(update_params)
    @answer.quizzes_id = @quizzes_id
    @quiz.update(quizzes_params) 
    # (questions_params)はしたの記述に由来している。answer以外の内容はストロングパラメータではじくよ
  end
  
  private
  def quizzes_params
    params.require(:answer).permit(:answer,:comment,:quizzes_id, ).merge(user_id: current_user.id)
  end
  
  def create_params
    params.require(:answer).permit(:answer,:comment,:quizzes_id, ).merge(user_id: current_user.id)
  end
  
  def update_params
    params.require(:answer).permit(:answer,:comment,:quizzes_id, ).merge(user_id: current_user.id)
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  def index
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/edit.html.erb
<html>
 <head></head>
 
 <body>
  <div class="bg-mask">
  <div class="qsedit">
   <!--< form_tag(quiz_path(@quiz), method: :patch) do %>-->
   <%= form_with(model:answer) do |f| %>
    <%= f.radio_button :answer,@quiz.choice1 %>
    <%= form.label :answer,@quiz.choice1,{value: @quiz.choice1} %>
    <%= f.radio_button :answer,@quiz.choice2 %>
    <%= form.label :answer,@quiz.choice2,{value: @quiz.choice2} %>
    <%= f.radio_button :answer,@quiz.choice3 %>
    <%= form.label :answer,@quiz.choice3,{value: @quiz.choice3} %>
    <%= f.hidden_field :quizzes_id %>
    <%= f.submit "回答" %>
   <% end %>
   

  </div>
  </div>
 </body>
</html>

app/views/quizzes/index.html.erb
 <body>
 
  <div class="bg-mask">
   <div class="title">Rails Quiz</div>
   
   <h1>問題一覧</h1>
   <div class="qsmenu">
    <% @quiz.each do |quiz| %>
      <%= quiz.title %>
      <%=link_to "問題へ", "/quizzes/#{quiz.id}/edit", method: :get  %><br>
    <% end %>
    
  </div>
    <%=link_to "トップへ", tops_path, method: :get  %>
 </body>
 
</html>

app/views/quizzes/update.html.erb
<html>
 <head></head>
 
 <body>
  <div class="bg-mask">
  <div class="qsupdate">
    <h5><%= @quiz.questions %></h5>
    <h2>正解</h2>
    <%= @quiz.c_answer %>
    <h5>あなたの回答</h5>
    <% if @quiz.c_answer == @quiz.answer %>
      <puts>○</puts>  <%= @quiz.answer %>
    <% else %>
      <puts>×</puts> <%= @quiz.answer %>
    <% end %>
    <h5>学習メモ</h5>
    <%= @quiz.comment %>
   
   
    <p><%= link_to '一覧へ戻る', quizzes_path, method: :get %></p>
  </div>
  </div>
 </body>
</html>

app/views/tops/index.html.erb
<html>
 <head></head>
 
 <body>
   <header>
    <% if user_signed_in? %>
      <h1>ようこそ<%=current_user.username %>さん　Rails Quizへ！</h1>
      <%=link_to "logout", destroy_user_session_path, method: :delete  %>
    <% else %>
     <%=link_to "login", new_user_session_path, method: :get  %>
    <% end %>
     
   </header>
  <div class="bg-mask">
   <div class="title">Rails Quiz</div>
   
   <div class="select">
      <%=link_to "問題",quizzes_path, method: :get %><br>
   </div>
   
   <!--<div class="select">-->
   <!--   <%=link_to "マイページ",user_path(current_user), method: :get %><br>-->
   </div>
  </div>
 </body>
 
</html>

app/views/users/show.html.erb
<body>
   <header>
    <% if user_signed_in? %>
      <h1><%=current_user.username %>さんの軌跡！</h1>
      <%=link_to "logout", destroy_user_session_path, method: :delete  %>
    <% else %>
     <%=link_to "login", new_user_session_path, method: :get  %>
    <% end %>
     <%=link_to "トップへ", tops_path, method: :get  %>
   </header>
  <div class="bg-mask">
   <h1>ここに問題の結果と問題ページ（edit）・回答ページ（update）をいれる</h1>
  </div>
 </body>